[package]
name = "transducer-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
automato = { path = "../../" }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
trybuild = "1.0"
